<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NetworkDoctor.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetworkDoctor.Core\NetworkDoctor.Core.csproj" />
  </ItemGroup>

</Project>
