<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetworkDoctor.Core\NetworkDoctor.Core.csproj" />
    <ProjectReference Include="..\NetworkDoctor.Windows\NetworkDoctor.Windows.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="4.3.0" />
  </ItemGroup>

</Project>
